### ISSUE TITLE
CUDA error: too many resources requested for launch

### ISSUE THREAD

**Issue by linzhenyuyuchen** [Gorilla-Lab-SCUT/HelixSurf#2]
```
(2/10): Fusing image and output depth/normal:  10%|█████████████████▉                                                                                                                                                                 | 1/10 [00:00<00:06,  1.40it/s]
Traceback (most recent call last):
  File "/home/anaconda3/envs/nerfmesh/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/envs/nerfmesh/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/HelixSurf_Project/gmvs/gmvs/scripts/launch.py", line 167, in <module>
    run_fusion(
  File "/home/HelixSurf_Project/gmvs/gmvs/consistency.py", line 191, in run_fusion
    proj_depth, proj_normal = Fuser.run_fusion(i, geom_consistent)
RuntimeError: CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by eehuangzhangjin** [comment]
Is the longest side of your image larger than 1024?  This is not supported yet!!!

We may support depth/normal fusion with large image later, or you could adaptively change the [code](https://github.com/Gorilla-Lab-SCUT/gmvs/blob/239b0b1051e48e2834bf0e023d1b789e4767ae4c/gmvs/src/fusion.cu#L251).

**Comment by Huang-ZhangJin** [comment]
We have fixed this issue in the newest commit.
