### ISSUE TITLE
ModuleNotFoundError: No module named 'prim3d'

### ISSUE THREAD

**Issue by small-zeng** [Gorilla-Lab-SCUT/HelixSurf#5]
using scene_id: 0616_00 train_suffix: 0616_00_pretrained vis_suffix: 0616_00_pretrained mvs_suffix: mvs **kwargs: --casting
Traceback (most recent call last):
  File "scripts/train_pretrained.py", line 17, in <module>
    from scripts.generate_normal import ray_casting_depth_normal
  File "/mnt/dataset/zengjing/HelixSurf/scripts/generate_normal.py", line 9, in <module>
    import prim3d
ModuleNotFoundError: No module named 'prim3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/train_pretrained.py", line 19, in <module>
    from generate_normal import ray_casting_depth_normal
  File "/mnt/dataset/zengjing/HelixSurf/scripts/generate_normal.py", line 9, in <module>
    import prim3d
ModuleNotFoundError: No module named 'prim3d'

**Comment by small-zeng** [comment]
When I run this code, the error occur, how to fix it?
